groups:
  - name: evgl.availability
    rules:
      - alert: EVGLServiceUnavailable
        expr: up{namespace=~"evgl.*"} == 0
        for: 5m
        labels: { severity: page }
        annotations:
          summary: "Evento Globolo service unavailable"
