apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: evgl-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/evento-globolo/evgl-infra.git
    targetRevision: main
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: evgl-dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions: [CreateNamespace=true]
