apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - evgl-api.yaml
  - evgl-mash-web.yaml
  - evgl-leptos-web.yaml
  - evgl-dioxus-web.yaml
  - evgl-sync.yaml
